[package]
name = "axum-api"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.17", features = ["headers"] }
jsonwebtoken = "8.3.0"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
